language: python
python:
  - "2.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio
  - platformio lib -g install 547
  - platformio lib -g install 306
  - platformio lib -g install 2678
  - platformio update

script:
  - platformio run
